# Generated by Django 4.2.2 on 2023-07-07 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Bankingapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="img",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="year",
        ),
    ]
