# Generated by Django 4.2.2 on 2023-07-07 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Bankingapp", "0002_remove_movie_img_remove_movie_year"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Movie",
            new_name="Login",
        ),
    ]
